import React, { useState } from 'react';
import { View, Text, TouchableOpacity, ScrollView } from 'react-native';
import { Card, Paragraph } from 'react-native-paper';

function AboutScreen() {
  const [isExpanded, setIsExpanded] = useState(false);

  const toggleExpand = () => {
    setIsExpanded(!isExpanded);
  };

  return (
    <View style={{ flex: 1, paddingHorizontal: 20, paddingTop: 20 }}>
      <ScrollView >
        {/* About */}
      <Card style={{ marginBottom: 20 }}>
        <Card.Title title="InsightInk - AI powered journal app" />
        <Card.Content>
          <Paragraph>
            Individuals require varied solutions as each person is inherently unique. 
            Frequently, the initial step in understanding one's mental state involves pinpointing the underlying cause. 
            This process of identification can manifest in diverse methods such as engaging in discussions with peers, 
            maintaining a journal, or recording audio reflections. However, there exists a caveat—many individuals may be 
            reluctant to share their innermost thoughts due to apprehension of ridicule. Despite the effectiveness of journaling 
            as a viable option, it lacks the capacity for external intervention to address underlying issues, 
            as journals primarily serve as repositories of personal thoughts. Consequently, seeking assistance from a third party 
            becomes imperative, albeit at the expense of privacy.
          </Paragraph>
          <Paragraph>
            InsightInk presents a solution by enabling users to transcribe their thoughts and leverage artificial intelligence 
            for sentiment analysis. This analytical framework furnishes users with novel perspectives on their internal reflections, 
            thereby fostering personal growth and introspection.
          </Paragraph>
        </Card.Content>
      </Card>

      {/* Disclaimer */}
      <Card style={{ backgroundColor: '#ffcccc', margin:8 }}>
        <Card.Title
          title="Disclaimer"
          right={(props) => (
            <TouchableOpacity onPress={toggleExpand}>
              <Text style={{ color: '#007bff', marginRight: 10 }}>{isExpanded ? 'Hide' : 'Show'}</Text>
            </TouchableOpacity>
          )}
        />
        {isExpanded && (
          <Card.Content>
            <Paragraph>
              This application serves as a prototype developed on the Vertex AI Gemini API, 
              graciously provided by Google Cloud. It is imperative to acknowledge that the feedback or 
              sentiment generated by the artificial intelligence (AI) should not be misconstrued as 
              medical advice, diagnosis, or treatment. Rather, it endeavors to facilitate AI-driven 
              interpretation of human thoughts, offering an alternative perspective on one's mental state.

              For any medical concerns, it is strongly advised to seek guidance from a qualified healthcare professional.
            </Paragraph>
          </Card.Content>
        )}
      </Card>
      </ScrollView>
    </View>
  );
}

AboutScreen.navigationOptions = {
  headerTitle: 'InsightInk'
}

export default AboutScreen;
